// Generated by l2js 0.0.1
var L2JS = require('l2js');
var _ENV = L2JS._G;
var L2JS$UNM = L2JS.unm;
var L2JS$LEN = L2JS.len;
var L2JS$TABLE = L2JS.table;
var L2JS$GET = L2JS.get;
var L2JS$SET = L2JS.set;
var L2JS$CALL = L2JS.call;
var L2JS$ADD = L2JS.add;
var L2JS$SUB = L2JS.sub;
var L2JS$MUL = L2JS.mul;
var L2JS$DIV = L2JS.div;
var L2JS$MOD = L2JS.mod;
var L2JS$POW = L2JS.pow;
var L2JS$EQ = L2JS.eq;
var L2JS$LT = L2JS.lt;
var L2JS$GT = L2JS.gt;
var L2JS$CONCAT = L2JS.concat;

(function*() {
var L2JS$TMP;
while(L2JS$TMP = (false || true), L2JS$TMP !== undefined && L2JS$TMP !== null && L2JS$TMP !== false) {
	var L2JS$TMP;
	break;
};
var L2JS$TMP;
yield* L2JS$CALL(yield* L2JS$GET(_ENV, "print"), [].concat("hi"));
;
do {
	var L2JS$TMP;
	var v2_a; L2JS$TMP = [].concat(yield* L2JS$GET(_ENV, "b")); v2_a = L2JS$TMP[0];
	break;
} while(((true || false) && true));
if(false) {
	var L2JS$TMP;
	var v3_a; L2JS$TMP = [].concat(yield* L2JS$GET(_ENV, "b")); v3_a = L2JS$TMP[0];
} else if(yield* L2JS$GET(_ENV, "hi")) {
	var L2JS$TMP;
} else {
	var L2JS$TMP;
};
yield* L2JS$CALL(yield* L2JS$GET(_ENV, "print"), [].concat((yield* L2JS$CONCAT("hello", (yield* L2JS$CONCAT(" ", "world"))))));

})().next()
