// Generated by l2js 0.0.1
var L2JS = require('l2js');
var _ENV = L2JS._G;
var L2JS$UNM = L2JS.unm;
var L2JS$LEN = L2JS.len;
var L2JS$TABLE = L2JS.table;
var L2JS$GET = L2JS.get;
var L2JS$SET = L2JS.set;
var L2JS$CALL = L2JS.call;
var L2JS$ADD = L2JS.add;
var L2JS$SUB = L2JS.sub;
var L2JS$MUL = L2JS.mul;
var L2JS$DIV = L2JS.div;
var L2JS$MOD = L2JS.mod;
var L2JS$POW = L2JS.pow;
var L2JS$EQ = L2JS.eq;
var L2JS$LT = L2JS.lt;
var L2JS$GT = L2JS.gt;
var L2JS$CONCAT = L2JS.concat;

var g = (function*() {
var L2JS$TMP;

})(); var res; do { res = g.next([]) } while(!res.done)
