local l2js = {}

l2js.parse = require 'lua-parser.parser'.parse
l2js.compile = require './compile'
l2js.header = [[
// Generated by l2js 0.0.1
var L2JS = require('l2js');
var _ENV = L2JS._G;
]]
for name in ('unm|len|table|get|set|call|add|sub|mul|div|mod|pow|eq|lt|gt|concat'):gmatch('([^|]+)') do
	l2js.header = l2js.header .. 'var L2JS$' .. name:upper() .. ' = L2JS.' .. name .. ';\n'
end

return l2js
